---
- name: Install puppetagent
  hosts: 172.31.39.43
  remote_user: root
  vars:
    - MASTER_IP: 172.31.36.2

  tasks:
    - name: install rpm package
      yum:
         name: https://yum.puppetlabs.com/puppet-release-el-7.noarch.rpm
         state: present

    - name: install puppet-agent
      yum:
          name: puppet-agent
          state: present

    - name: get ip
      shell: hostname -I
      register: IP

    - name: add host entry
      blockinfile:
        path: /etc/hosts
        block: |
               {{ IP.stdout }} agent.suvishesh.com
               {{ MASTER_IP }} master.suvishesh.com
        state: present

    - name: add puppet config
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
               [agent]
               server = master.suvishesh.com
        state: present

    - name: start the service
      command: sudo /opt/puppetlabs/bin/puppet resource service puppet ensure=running enable=true

    - name: requesting the master to sign certificate
      command: /opt/puppetlabs/bin/puppet agent -t
      ignore_errors: yes
